In [ ]:
import pandas as pd
import numpy as np

# ==========================================
# 1. CONCATENATION OF DATAFRAMES
# ==========================================

dataFrame1 = pd.read_csv('/content/Auto.csv')
dataFrame2 = pd.read_csv('/content/Bank_Churn.csv')

# Vertical Concatenation
vertical_concat = pd.concat([dataFrame1, dataFrame2], ignore_index=True)
print("Vertical Concatenation:")
print(vertical_concat)

# Horizontal Concatenation
horizontal_concat = pd.concat([dataFrame1, dataFrame2], axis=1)
print("\nHorizontal Concatenation:")
print(horizontal_concat)

Vertical Concatenation:
        mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0      18.0        8.0         307.0       130.0  3504.0          12.0  70.0
1      15.0        8.0         350.0       165.0  3693.0          11.5  70.0
2      18.0        8.0         318.0       150.0  3436.0          11.0  70.0
3      16.0        8.0         304.0       150.0  3433.0          12.0  70.0
4      17.0        8.0         302.0       140.0  3449.0          10.5  70.0
...     ...        ...           ...         ...     ...           ...   ...
10387   NaN        NaN           NaN         NaN     NaN           NaN   NaN
10388   NaN        NaN           NaN         NaN     NaN           NaN   NaN
10389   NaN        NaN           NaN         NaN     NaN           NaN   NaN
10390   NaN        NaN           NaN         NaN     NaN           NaN   NaN
10391   NaN        NaN           NaN         NaN     NaN           NaN   NaN

       origin                       name  CustomerId  ... Geography  Gender  \
0         1.0  chevrolet chevelle malibu         NaN  ...       NaN     NaN
1         1.0          buick skylark 320         NaN  ...       NaN     NaN
2         1.0         plymouth satellite         NaN  ...       NaN     NaN
3         1.0              amc rebel sst         NaN  ...       NaN     NaN
4         1.0                ford torino         NaN  ...       NaN     NaN
...       ...                        ...         ...  ...       ...     ...
10387     NaN                        NaN  15606229.0  ...    France    Male
10388     NaN                        NaN  15569892.0  ...    France    Male
10389     NaN                        NaN  15584532.0  ...    France  Female
10390     NaN                        NaN  15682355.0  ...   Germany    Male
10391     NaN                        NaN  15628319.0  ...    France  Female

        Age Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       NaN    NaN        NaN            NaN        NaN             NaN
1       NaN    NaN        NaN            NaN        NaN             NaN
2       NaN    NaN        NaN            NaN        NaN             NaN
3       NaN    NaN        NaN            NaN        NaN             NaN
4       NaN    NaN        NaN            NaN        NaN             NaN
...     ...    ...        ...            ...        ...             ...
10387  39.0    5.0       0.00            2.0        1.0             0.0
10388  35.0   10.0   57369.61            1.0        1.0             1.0
10389  36.0    7.0       0.00            1.0        0.0             1.0
10390  42.0    3.0   75075.31            2.0        1.0             0.0
10391  28.0    4.0  130142.79            1.0        1.0             0.0

       EstimatedSalary  Exited
0                  NaN     NaN
1                  NaN     NaN
2                  NaN     NaN
3                  NaN     NaN
4                  NaN     NaN
...                ...     ...
10387         96270.64     0.0
10388        101699.77     0.0
10389         42085.58     1.0
10390         92888.52     1.0
10391         38190.78     0.0

[10392 rows x 22 columns]

Horizontal Concatenation:
       mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0     18.0        8.0         307.0       130.0  3504.0          12.0  70.0
1     15.0        8.0         350.0       165.0  3693.0          11.5  70.0
2     18.0        8.0         318.0       150.0  3436.0          11.0  70.0
3     16.0        8.0         304.0       150.0  3433.0          12.0  70.0
4     17.0        8.0         302.0       140.0  3449.0          10.5  70.0
...    ...        ...           ...         ...     ...           ...   ...
9995   NaN        NaN           NaN         NaN     NaN           NaN   NaN
9996   NaN        NaN           NaN         NaN     NaN           NaN   NaN
9997   NaN        NaN           NaN         NaN     NaN           NaN   NaN
9998   NaN        NaN           NaN         NaN     NaN           NaN   NaN
9999   NaN        NaN           NaN         NaN     NaN           NaN   NaN

      origin                       name  CustomerId  ... Geography  Gender  \
0        1.0  chevrolet chevelle malibu    15634602  ...    France  Female
1        1.0          buick skylark 320    15647311  ...     Spain  Female
2        1.0         plymouth satellite    15619304  ...    France  Female
3        1.0              amc rebel sst    15701354  ...    France  Female
4        1.0                ford torino    15737888  ...     Spain  Female
...      ...                        ...         ...  ...       ...     ...
9995     NaN                        NaN    15606229  ...    France    Male
9996     NaN                        NaN    15569892  ...    France    Male
9997     NaN                        NaN    15584532  ...    France  Female
9998     NaN                        NaN    15682355  ...   Germany    Male
9999     NaN                        NaN    15628319  ...    France  Female

     Age Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0     42      2       0.00              1          1               1
1     41      1   83807.86              1          0               1
2     42      8  159660.80              3          1               0
3     39      1       0.00              2          0               0
4     43      2  125510.82              1          1               1
...   ..    ...        ...            ...        ...             ...
9995  39      5       0.00              2          1               0
9996  35     10   57369.61              1          1               1
9997  36      7       0.00              1          0               1
9998  42      3   75075.31              2          1               0
9999  28      4  130142.79              1          1               0

      EstimatedSalary  Exited
0           101348.88       1
1           112542.58       0
2           113931.57       1
3            93826.63       0
4            79084.10       0
...               ...     ...
9995         96270.64       0
9996        101699.77       0
9997         42085.58       1
9998         92888.52       1
9999         38190.78       0

[10000 rows x 22 columns]

# 2. MERGING `Auto.csv` and `Bank_Churn.csv`

As `Auto.csv` (`dataFrame1`) and `Bank_Churn.csv` (`dataFrame2`) do not share common columns for a natural merge, we will add a dummy `merge_key` column to both DataFrames. This will allow us to demonstrate different types of merges (inner, left, right, outer) between these two datasets. Note that merging on a dummy key often results in a cross-join, which combines every row from one DataFrame with every row from the other.

In [ ]:
# Add a dummy merge_key to both DataFrames
dataFrame1['merge_key'] = 1
dataFrame2['merge_key'] = 1

print("DataFrame1 (Auto.csv) with merge_key:")
display(dataFrame1.head())
print("\nDataFrame2 (Bank_Churn.csv) with merge_key:")
display(dataFrame2.head())

DataFrame1 (Auto.csv) with merge_key:

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name,merge_key
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu,1
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320,1
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite,1
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst,1
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino,1

DataFrame2 (Bank_Churn.csv) with merge_key:

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,merge_key
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,1
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,1

In [ ]:
# Inner Join
# Since both dataframes have only one 'merge_key' value (1), an inner join on this key will produce a Cartesian product.
inner_join_auto_bank = pd.merge(dataFrame1, dataFrame2, on='merge_key', how='inner')
print("\nInner Join of Auto.csv and Bank_Churn.csv (using dummy key):")
print(inner_join_auto_bank.head())
print(f"Shape of Inner Join: {inner_join_auto_bank.shape}")

# Left Join
left_join_auto_bank = pd.merge(dataFrame1, dataFrame2, on='merge_key', how='left')
print("\nLeft Join of Auto.csv and Bank_Churn.csv (using dummy key):")
print(left_join_auto_bank.head())
print(f"Shape of Left Join: {left_join_auto_bank.shape}")

# Right Join
right_join_auto_bank = pd.merge(dataFrame1, dataFrame2, on='merge_key', how='right')
print("\nRight Join of Auto.csv and Bank_Churn.csv (using dummy key):")
print(right_join_auto_bank.head())
print(f"Shape of Right Join: {right_join_auto_bank.shape}")

# Outer Join
outer_join_auto_bank = pd.merge(dataFrame1, dataFrame2, on='merge_key', how='outer')
print("\nOuter Join of Auto.csv and Bank_Churn.csv (using dummy key):")
print(outer_join_auto_bank.head())
print(f"Shape of Outer Join: {outer_join_auto_bank.shape}")

Inner Join of Auto.csv and Bank_Churn.csv (using dummy key):
    mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0         130    3504          12.0    70
1  18.0          8         307.0         130    3504          12.0    70
2  18.0          8         307.0         130    3504          12.0    70
3  18.0          8         307.0         130    3504          12.0    70
4  18.0          8         307.0         130    3504          12.0    70

   origin                       name  merge_key  ...  Geography  Gender  Age  \
0       1  chevrolet chevelle malibu          1  ...     France  Female   42
1       1  chevrolet chevelle malibu          1  ...      Spain  Female   41
2       1  chevrolet chevelle malibu          1  ...     France  Female   42
3       1  chevrolet chevelle malibu          1  ...     France  Female   39
4       1  chevrolet chevelle malibu          1  ...      Spain  Female   43

  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0      2       0.00              1          1               1
1      1   83807.86              1          0               1
2      8  159660.80              3          1               0
3      1       0.00              2          0               0
4      2  125510.82              1          1               1

   EstimatedSalary  Exited
0        101348.88       1
1        112542.58       0
2        113931.57       1
3         93826.63       0
4         79084.10       0

[5 rows x 23 columns]
Shape of Inner Join: (3920000, 23)

Left Join of Auto.csv and Bank_Churn.csv (using dummy key):
    mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0         130    3504          12.0    70
1  18.0          8         307.0         130    3504          12.0    70
2  18.0          8         307.0         130    3504          12.0    70
3  18.0          8         307.0         130    3504          12.0    70
4  18.0          8         307.0         130    3504          12.0    70

   origin                       name  merge_key  ...  Geography  Gender  Age  \
0       1  chevrolet chevelle malibu          1  ...     France  Female   42
1       1  chevrolet chevelle malibu          1  ...      Spain  Female   41
2       1  chevrolet chevelle malibu          1  ...     France  Female   42
3       1  chevrolet chevelle malibu          1  ...     France  Female   39
4       1  chevrolet chevelle malibu          1  ...      Spain  Female   43

  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0      2       0.00              1          1               1
1      1   83807.86              1          0               1
2      8  159660.80              3          1               0
3      1       0.00              2          0               0
4      2  125510.82              1          1               1

   EstimatedSalary  Exited
0        101348.88       1
1        112542.58       0
2        113931.57       1
3         93826.63       0
4         79084.10       0

[5 rows x 23 columns]
Shape of Left Join: (3920000, 23)

Right Join of Auto.csv and Bank_Churn.csv (using dummy key):
    mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0         130    3504          12.0    70
1  15.0          8         350.0         165    3693          11.5    70
2  18.0          8         318.0         150    3436          11.0    70
3  16.0          8         304.0         150    3433          12.0    70
4  17.0          8         302.0         140    3449          10.5    70

   origin                       name  merge_key  ...  Geography  Gender  Age  \
0       1  chevrolet chevelle malibu          1  ...     France  Female   42
1       1          buick skylark 320          1  ...     France  Female   42
2       1         plymouth satellite          1  ...     France  Female   42
3       1              amc rebel sst          1  ...     France  Female   42
4       1                ford torino          1  ...     France  Female   42

  Tenure Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  \
0      2     0.0              1          1               1        101348.88
1      2     0.0              1          1               1        101348.88
2      2     0.0              1          1               1        101348.88
3      2     0.0              1          1               1        101348.88
4      2     0.0              1          1               1        101348.88

   Exited
0       1
1       1
2       1
3       1
4       1

[5 rows x 23 columns]
Shape of Right Join: (3920000, 23)

Outer Join of Auto.csv and Bank_Churn.csv (using dummy key):
    mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0         130    3504          12.0    70
1  18.0          8         307.0         130    3504          12.0    70
2  18.0          8         307.0         130    3504          12.0    70
3  18.0          8         307.0         130    3504          12.0    70
4  18.0          8         307.0         130    3504          12.0    70

   origin                       name  merge_key  ...  Geography  Gender  Age  \
0       1  chevrolet chevelle malibu          1  ...     France  Female   42
1       1  chevrolet chevelle malibu          1  ...      Spain  Female   41
2       1  chevrolet chevelle malibu          1  ...     France  Female   42
3       1  chevrolet chevelle malibu          1  ...     France  Female   39
4       1  chevrolet chevelle malibu          1  ...      Spain  Female   43

  Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0      2       0.00              1          1               1
1      1   83807.86              1          0               1
2      8  159660.80              3          1               0
3      1       0.00              2          0               0
4      2  125510.82              1          1               1

   EstimatedSalary  Exited
0        101348.88       1
1        112542.58       0
2        113931.57       1
3         93826.63       0
4         79084.10       0

[5 rows x 23 columns]
Shape of Outer Join: (3920000, 23)