## Merging DataFrames with a New Dataset (Raining Data)

Let's create two new DataFrames, `df_temp` (temperature data) and `df_humidity` (humidity data), to demonstrate the different merging options. Both will have a 'Date' column, and we'll ensure some dates overlap and some don't, to clearly show the effects of different join types.

In [6]:
import pandas as pd


# Temperature data
df_temp = pd.DataFrame({
    'Date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-05', '2023-01-06'],
    'Avg_Temperature_C': [10, 12, 11, 15, 13],
    'City': ['London', 'London', 'London', 'London', 'London']
})

# Humidity data
df_humidity = pd.DataFrame({
    'Date': ['2023-01-02', '2023-01-03', '2023-01-04', '2023-01-06', '2023-01-07'],
    'Avg_Humidity_Perc': [85, 90, 88, 92, 80],
    'City': ['London', 'London', 'London', 'London', 'London']
})

print("df_temp:")
display(df_temp)
print("\ndf_humidity:")
display(df_humidity)

df_temp:

         Date  Avg_Temperature_C    City
0  2023-01-01                 10  London
1  2023-01-02                 12  London
2  2023-01-03                 11  London
3  2023-01-05                 15  London
4  2023-01-06                 13  London

df_humidity:

         Date  Avg_Humidity_Perc    City
0  2023-01-02                 85  London
1  2023-01-03                 90  London
2  2023-01-04                 88  London
3  2023-01-06                 92  London
4  2023-01-07                 80  London

### Option 1: Concatenating DataFrames (axis=1)

In [7]:
df_concat_axis1 = pd.concat([df_temp, df_humidity], axis=1)
print("Concatenated DataFrame (axis=1):")
display(df_concat_axis1)

Concatenated DataFrame (axis=1):

,Date,Avg_Temperature_C,City,Date,Avg_Humidity_Perc,City
0,2023-01-01,10,London,2023-01-02,85,London
1,2023-01-02,12,London,2023-01-03,90,London
2,2023-01-03,11,London,2023-01-04,88,London
3,2023-01-05,15,London,2023-01-06,92,London
4,2023-01-06,13,London,2023-01-07,80,London

### Option 2: Inner Merge

In [8]:
df_inner_merge = df_temp.merge(df_humidity, on='Date', how='inner')
print("Inner Merged DataFrame:")
display(df_inner_merge)

Inner Merged DataFrame:

         Date  Avg_Temperature_C  City_x  Avg_Humidity_Perc  City_y
0  2023-01-02                 12  London                 85  London
1  2023-01-03                 11  London                 90  London
2  2023-01-06                 13  London                 92  London

### Option 3: Left Merge

In [9]:
df_left_merge = df_temp.merge(df_humidity, on='Date', how='left')
print("Left Merged DataFrame:")
display(df_left_merge)

Left Merged DataFrame:

         Date  Avg_Temperature_C  City_x  Avg_Humidity_Perc  City_y
0  2023-01-01                 10  London                NaN     NaN
1  2023-01-02                 12  London               85.0  London
2  2023-01-03                 11  London               90.0  London
3  2023-01-05                 15  London                NaN     NaN
4  2023-01-06                 13  London               92.0  London

### Option 4: Right Merge

In [10]:
df_right_merge = df_temp.merge(df_humidity, on='Date', how='right')
print("Right Merged DataFrame:")
display(df_right_merge)

Right Merged DataFrame:

         Date  Avg_Temperature_C  City_x  Avg_Humidity_Perc  City_y
0  2023-01-02               12.0  London                 85  London
1  2023-01-03               11.0  London                 90  London
2  2023-01-04                NaN     NaN                 88  London
3  2023-01-06               13.0  London                 92  London
4  2023-01-07                NaN     NaN                 80  London

## Reshaping with Hierarchical Indexing

This section demonstrates how to reshape data using `stack()` and `unstack()` methods, which are powerful tools for working with hierarchical indices in Pandas DataFrames and Series.

In [12]:
import numpy as np

data = np.arange(15).reshape((3,5))
indexers = ['Rainfall', 'Humidity', 'Wind']
dframe1 = pd.DataFrame(data, index=indexers, columns=['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Kristiansand'])
print("Original DataFrame (dframe1):")
display(dframe1)

Original DataFrame (dframe1):

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

### Using `stack()`

In [13]:
stacked = dframe1.stack()
print("Stacked Series:")
display(stacked)

Stacked Series:

Rainfall  Bergen           0
          Oslo             1
          Trondheim        2
          Stavanger        3
          Kristiansand     4
Humidity  Bergen           5
          Oslo             6
          Trondheim        7
          Stavanger        8
          Kristiansand     9
Wind      Bergen          10
          Oslo            11
          Trondheim       12
          Stavanger       13
          Kristiansand    14
dtype: int64

### Using `unstack()`

In [14]:
unstacked = stacked.unstack()
print("Unstacked DataFrame (back to original shape):")
display(unstacked)

Unstacked DataFrame (back to original shape):

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

### Concatenating Series with Hierarchical Keys and `unstack()`

In [15]:
series1 = pd.Series([000, 111, 222, 333], index=['zeros','ones', 'twos', 'threes'])
series2 = pd.Series([444, 555, 666], index=['fours', 'fives', 'sixs'])

print("series1:")
display(series1)
print("\nseries2:")
display(series2)

frame2 = pd.concat([series1, series2], keys=['Number1', 'Number2'])
print("\nConcatenated Series with hierarchical keys:")
display(frame2)

series1:

zeros       0
ones      111
twos      222
threes    333
dtype: int64

series2:

fours    444
fives    555
sixs     666
dtype: int64

Concatenated Series with hierarchical keys:

Number1  zeros       0
         ones      111
         twos      222
         threes    333
Number2  fours     444
         fives     555
         sixs      666
dtype: int64

In [16]:
unstacked_frame2 = frame2.unstack()
print("Unstacked DataFrame from concatenated Series:")
display(unstacked_frame2)

Unstacked DataFrame from concatenated Series:

         fives  fours   ones   sixs  threes   twos  zeros
Number1    NaN    NaN  111.0    NaN   333.0  222.0    0.0
Number2  555.0  444.0    NaN  666.0     NaN    NaN    NaN