<a href="https://colab.research.google.com/github/Shanmukh5922/Exploratory_data_analysis/blob/main/25BAI0140_EXP4_28.07.2026/MissingValues2_ImputationTechniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer

df_new = pd.DataFrame(
    {
        "Feature1": [10, np.nan, 15, 20, 12],
        "Feature2": [100, 120, np.nan, 150, 110],
        "Feature3": ["X", "Y", "X", np.nan, "Y"],
    }
)

mean_imputer_new = SimpleImputer(strategy="mean")
df_new["Feature1_Mean"] = mean_imputer_new.fit_transform(df_new[["Feature1"]])

median_imputer_new = SimpleImputer(strategy="median")
df_new["Feature2_Median"] = median_imputer_new.fit_transform(df_new[["Feature2"]])

mode_imputer_new = SimpleImputer(strategy="most_frequent")
df_new["Feature3_Mode"] = mode_imputer_new.fit_transform(df_new[["Feature3"]])[:, 0]

num_cols_new = ["Feature1", "Feature2"]
mice_imputer_new = IterativeImputer(max_iter=10, random_state=42)
df_mice_new = df_new[num_cols_new].copy()
df_mice_new.iloc[:, :] = mice_imputer_new.fit_transform(df_mice_new)
df_new["Feature1_MICE"] = df_mice_new["Feature1"]
df_new["Feature2_MICE"] = df_mice_new["Feature2"]
print(df_new)

   Feature1  Feature2 Feature3  Feature1_Mean  Feature2_Median Feature3_Mode  \
0      10.0     100.0        X          10.00            100.0             X
1       NaN     120.0        Y          14.25            120.0             Y
2      15.0       NaN        X          15.00            115.0             X
3      20.0     150.0      NaN          20.00            150.0             X
4      12.0     110.0        Y          12.00            110.0             Y

   Feature1_MICE  Feature2_MICE
0       10.00000     100.000000
1       14.00097     120.000000
2       15.00000     124.998788
3       20.00000     150.000000
4       12.00000     110.000000

## Missing Values

In [11]:
data_new = {
    'Product': ['A', 'B', 'C', 'D', 'E', 'F'],
    'Sales_Q1': [100, 150, np.nan, 120, 200, 80],
    'Sales_Q2': [np.nan, 160, 110, 130, np.nan, 90],
    'Region': ['East', 'West', 'North', np.nan, 'East', 'South'],
    'Units_Sold': [10, 15, 11, np.nan, np.nan, 8]
}
df_products = pd.DataFrame(data_new)
df_products.loc[6] = ['G', np.nan, np.nan, np.nan, np.nan]
df_products.loc[7] = [np.nan, np.nan, np.nan, np.nan, np.nan]
df_products['Notes'] = np.nan
display(df_products)

  Product  Sales_Q1  Sales_Q2 Region  Units_Sold  Notes
0       A     100.0       NaN   East        10.0    NaN
1       B     150.0     160.0   West        15.0    NaN
2       C       NaN     110.0  North        11.0    NaN
3       D     120.0     130.0    NaN         NaN    NaN
4       E     200.0       NaN   East         NaN    NaN
5       F      80.0      90.0  South         8.0    NaN
6       G       NaN       NaN    NaN         NaN    NaN
7     NaN       NaN       NaN    NaN         NaN    NaN

In [12]:
display(df_products.isnull())

display(df_products.notnull())

   Product  Sales_Q1  Sales_Q2  Region  Units_Sold  Notes
0    False     False      True   False       False   True
1    False     False     False   False       False   True
2    False      True     False   False       False   True
3    False     False     False    True        True   True
4    False     False      True   False        True   True
5    False     False     False   False       False   True
6    False      True      True    True        True   True
7     True      True      True    True        True   True

   Product  Sales_Q1  Sales_Q2  Region  Units_Sold  Notes
0     True      True     False    True        True  False
1     True      True      True    True        True  False
2     True     False      True    True        True  False
3     True      True      True   False       False  False
4     True      True     False    True       False  False
5     True      True      True    True        True  False
6     True     False     False   False       False  False
7    False     False     False   False       False  False

In [13]:
print("Number of NaN values per column:")
display(df_products.isnull().sum())

print("Total number of NaN values in the DataFrame:")
display(df_products.isnull().sum().sum())

Number of NaN values per column:

Product       1
Sales_Q1      3
Sales_Q2      4
Region        3
Units_Sold    4
Notes         8
dtype: int64

Total number of NaN values in the DataFrame:

np.int64(23)

In [14]:
print("Number of reported (non-NaN) values per column:")
display(df_products.count())

Number of reported (non-NaN) values per column:

Product       7
Sales_Q1      5
Sales_Q2      4
Region        5
Units_Sold    4
Notes         0
dtype: int64

In [15]:
print("DataFrame after dropping rows with any NaN:")
display(df_products.dropna())

print("DataFrame after dropping rows where ALL values are NaN (how='all'):")
display(df_products.dropna(how='all'))

print("DataFrame after dropping columns where ALL values are NaN (axis=1, how='all'):")
display(df_products.dropna(axis=1, how='all'))

print("DataFrame after dropping rows with less than 4 non-NaN values (thresh=4):")
display(df_products.dropna(thresh=4))

DataFrame after dropping rows with any NaN:

Empty DataFrame
Columns: [Product, Sales_Q1, Sales_Q2, Region, Units_Sold, Notes]
Index: []

DataFrame after dropping rows where ALL values are NaN (how='all'):

  Product  Sales_Q1  Sales_Q2 Region  Units_Sold  Notes
0       A     100.0       NaN   East        10.0    NaN
1       B     150.0     160.0   West        15.0    NaN
2       C       NaN     110.0  North        11.0    NaN
3       D     120.0     130.0    NaN         NaN    NaN
4       E     200.0       NaN   East         NaN    NaN
5       F      80.0      90.0  South         8.0    NaN
6       G       NaN       NaN    NaN         NaN    NaN

DataFrame after dropping columns where ALL values are NaN (axis=1, how='all'):

  Product  Sales_Q1  Sales_Q2 Region  Units_Sold
0       A     100.0       NaN   East        10.0
1       B     150.0     160.0   West        15.0
2       C       NaN     110.0  North        11.0
3       D     120.0     130.0    NaN         NaN
4       E     200.0       NaN   East         NaN
5       F      80.0      90.0  South         8.0
6       G       NaN       NaN    NaN         NaN
7     NaN       NaN       NaN    NaN         NaN

DataFrame after dropping rows with less than 4 non-NaN values (thresh=4):

  Product  Sales_Q1  Sales_Q2 Region  Units_Sold  Notes
0       A     100.0       NaN   East        10.0    NaN
1       B     150.0     160.0   West        15.0    NaN
2       C       NaN     110.0  North        11.0    NaN
5       F      80.0      90.0  South         8.0    NaN

In [16]:
print(f"Mean of Sales_Q1: {df_products['Sales_Q1'].mean()}")
print(f"Sum of Sales_Q2: {df_products['Sales_Q2'].sum()}")

print("Cumulative sum for Units_Sold:")
display(df_products['Units_Sold'].cumsum())

Mean of Sales_Q1: 130.0
Sum of Sales_Q2: 490.0
Cumulative sum for Units_Sold:

0    10.0
1    25.0
2    36.0
3     NaN
4     NaN
5    44.0
6     NaN
7     NaN
Name: Units_Sold, dtype: float64

In [17]:
print("DataFrame after filling NaNs with 0:")
filled_df_zero = df_products.fillna(0)
display(filled_df_zero)

print(f"Mean of Sales_Q1 (original): {df_products['Sales_Q1'].mean()}")
print(f"Mean of Sales_Q1 (filled with 0): {filled_df_zero['Sales_Q1'].mean()}")

print("DataFrame after forward-filling 'Sales_Q2':")
display(df_products['Sales_Q2'].fillna(method='ffill'))

print("DataFrame after backward-filling 'Region':")
display(df_products['Region'].fillna(method='bfill'))

DataFrame after filling NaNs with 0:

  Product  Sales_Q1  Sales_Q2 Region  Units_Sold  Notes
0       A     100.0       0.0   East        10.0    0.0
1       B     150.0     160.0   West        15.0    0.0
2       C       0.0     110.0  North        11.0    0.0
3       D     120.0     130.0      0         0.0    0.0
4       E     200.0       0.0   East         0.0    0.0
5       F      80.0      90.0  South         8.0    0.0
6       G       0.0       0.0      0         0.0    0.0
7       0       0.0       0.0      0         0.0    0.0

Mean of Sales_Q1 (original): 130.0
Mean of Sales_Q1 (filled with 0): 81.25
DataFrame after forward-filling 'Sales_Q2':

/tmp/ipykernel_3376/2612582847.py:9: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display(df_products['Sales_Q2'].fillna(method='ffill'))

0      NaN
1    160.0
2    110.0
3    130.0
4    130.0
5     90.0
6     90.0
7     90.0
Name: Sales_Q2, dtype: float64

DataFrame after backward-filling 'Region':

/tmp/ipykernel_3376/2612582847.py:12: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  display(df_products['Region'].fillna(method='bfill'))

0     East
1     West
2    North
3     East
4     East
5    South
6      NaN
7      NaN
Name: Region, dtype: object

Missing values